# Generated by Django 5.0.4 on 2024-05-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discounted_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
