# Generated by Django 5.0.4 on 2024-05-15 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_product_discounted_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='orignal_price',
            new_name='original_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discounted_price',
        ),
    ]
